name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/auth@v1
        with:
            deliverables: backend-kotlin/app.yaml
            credentials_json: ${{ secrets.GCP_SA_KEY }}
            service_account: 'test-892@vidbox-7d2c1.iam.gserviceaccount.com
'

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
