name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          service_account: 'test-892@vidbox-7d2c1.iam.gserviceaccount.com'

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          working_directory: backend-kotlin
          deliverables: app.yaml

      - name: Cleanup old versions
        run: |
          gcloud app versions list --service default --format 'value(id)' --sort-by '~version' \
          | tail -n +2 \
          | xargs gcloud app versions delete --service default
