name: Push to docker, deploy to render

on:
  push:
    branches:
      - main
    paths:
      - 'backend-kotlin/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend-kotlin
          push: true
          tags: vg116/vidbox-backend:latest
          build-args: VIDBOX_JSON = ${{ secrets.VIDBOX_JSON }}

      - name: Trigger Render Deployment
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
